#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_APP_USER}') THEN
    CREATE ROLE ${POSTGRES_APP_USER} LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_DEBEZIUM_USER}') THEN
    CREATE ROLE ${POSTGRES_DEBEZIUM_USER} LOGIN REPLICATION PASSWORD '${POSTGRES_DEBEZIUM_PASSWORD}';
  END IF;
END
\$\$;

CREATE TABLE IF NOT EXISTS public.customers (
  id BIGSERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.customers REPLICA IDENTITY FULL;
SELECT 'CREATE PUBLICATION platform_customers_publication FOR TABLE public.customers'
WHERE NOT EXISTS (
  SELECT 1 FROM pg_publication WHERE pubname = 'platform_customers_publication'
) \gexec

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER}, ${POSTGRES_DEBEZIUM_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER}, ${POSTGRES_DEBEZIUM_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_APP_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_APP_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_DEBEZIUM_USER};

INSERT INTO public.customers (email, full_name, status)
SELECT 'seed@example.test', 'Seed Customer', 'active'
WHERE NOT EXISTS (SELECT 1 FROM public.customers);
EOSQL
